sudo: false

language: python

python:
  - 3.5

addons:
  apt:
    packages:
      - gettext
      - nodejs

cache:
  directories:
  - node_modules

install:
  - make requirements

script:
  - make build
  - make test
  - make validate_translations
#  - make check_translations_up_to_date
