language: python
os: linux
dist: focal

python:
  - 3.8

addons:
  apt:
    packages:
      - gettext
      - nodejs

cache:
  directories:
  - node_modules

install:
  - make requirements
  - pip install -r requirements/travis.txt

script:
  - make build
  - make test
  - make validate_translations
